export const LIST_CHANNEL = 'LIST_CHANNEL';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const LEAVE_CHANNEL = 'LEAVE_CHANNEL';
export const PUSH_MESSAGE_CHANNEL = 'PUSH_MESSAGE_CHANNEL';
export const PULL_MESSAGE_CHANNEL = 'PULL_MESSAGE_CHANNEL';
export const CLEAN_CHANNEL_MESSAGES = 'CLEAN_CHANNEL_MESSAGES';
